language: java
sudo: false # faster builds
jdk:
- oraclejdk8

script: "mvn cobertura:cobertura"


after_success:
  - bash <(curl -s https://codecov.io/bash)-t 473512dd-b845-4280-b4ab-ae8988a5dffd
  

